AllCops:
  TargetRubyVersion: 2.7.1

Metrics/BlockLength:
  Max: 25
  ExcludedMethods: [describe, context, group]

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 20
